name: DFD Build and Deploy

on: [push]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build & Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: dglinux/dfd
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ${{ github.workspace }}/Dockerfile
          workdir: ${{ github.workspace }}